/* Generated By:JavaCC: Do not edit this line. PsyScriptParserConstants.java */
package net.bramp.psyscript.parser;

public interface PsyScriptParserConstants {

  int EOF = 0;
  int WHITESPACE = 1;
  int SINGLE_LINE_COMMENT = 2;
  int STRING_INTO_END = 3;
  int STRING_IS_END = 4;
  int STRING_IN_END = 5;
  int STRING_SYMBOL_END = 6;
  int STRING_SIZE_END = 7;
  int STRING_AT_END = 8;
  int STRING_WITHOUT_END = 9;
  int TABLE_STRING_END = 10;
  int STRING_END = 11;
  int STRING = 12;
  int INTEGER = 13;
  int FLOAT = 14;
  int EXPONENT = 15;
  int NEWLINE = 16;
  int END = 17;
  int TABLE = 18;
  int IN = 19;
  int RANDOM = 20;
  int ORDER = 21;
  int COMMA = 22;
  int LBRACKET = 23;
  int RBRACKET = 24;
  int A = 25;
  int AT = 26;
  int ABORT = 27;
  int APPEND = 28;
  int BACKGROUND = 29;
  int BUFFER = 30;
  int BY = 31;
  int CALL = 32;
  int CELL = 33;
  int CELLS = 34;
  int CLICK = 35;
  int COUNTDOWN = 36;
  int CURSOR = 37;
  int DISPLAY = 38;
  int DURATION = 39;
  int ELSE = 40;
  int FIELD = 41;
  int FILE = 42;
  int FLUSH = 43;
  int FONT = 44;
  int FOR = 45;
  int FROM = 46;
  int HIDE = 47;
  int HTML = 48;
  int IF = 49;
  int IMAGE = 50;
  int IS = 51;
  int INTO = 52;
  int KEY = 53;
  int LOAD = 54;
  int LOG = 55;
  int MOVE = 56;
  int MOVIE = 57;
  int OF = 58;
  int OR = 59;
  int PAUSE = 60;
  int PLAIN = 61;
  int PLAY = 62;
  int PROCEDURE = 63;
  int REMOVE = 64;
  int RICH = 65;
  int REPEAT = 66;
  int ROW = 67;
  int ROWS = 68;
  int SECOND = 69;
  int SECONDS = 70;
  int SET = 71;
  int SHOW = 72;
  int SIZE = 73;
  int SKIP_ = 74;
  int SLIDER = 75;
  int SOUND = 76;
  int START = 77;
  int TEXT = 78;
  int TIMER = 79;
  int TO = 80;
  int UNTIL = 81;
  int USING = 82;
  int WAIT = 83;
  int WAITING = 84;
  int WHILE = 85;
  int WITHSIZE = 86;
  int WITHOUT = 87;
  int IDENTIFIER = 88;
  int LETTER = 89;
  int DIGIT = 90;
  int CHARACTER = 91;
  int VARIABLE = 92;

  int DEFAULT = 0;
  int IN_STRING_NO_INTO = 1;
  int IN_STRING_NO_IS = 2;
  int IN_STRING_NO_IN = 3;
  int IN_STRING_NO_SYMBOL = 4;
  int IN_STRING_NO_SIZE = 5;
  int IN_STRING_NO_AT = 6;
  int IN_STRING_NO_WITHOUT = 7;
  int IN_TABLE_STRING = 8;
  int IN_STRING = 9;
  int IN_INTEGER = 10;
  int IN_FLOAT = 11;
  int IN_TABLE = 12;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "<STRING_INTO_END>",
    "<STRING_IS_END>",
    "<STRING_IN_END>",
    "<STRING_SYMBOL_END>",
    "<STRING_SIZE_END>",
    "<STRING_AT_END>",
    "<STRING_WITHOUT_END>",
    "<TABLE_STRING_END>",
    "<STRING_END>",
    "<STRING>",
    "<INTEGER>",
    "<FLOAT>",
    "<EXPONENT>",
    "<NEWLINE>",
    "\"end\"",
    "\"table\"",
    "\"in\"",
    "\"random\"",
    "\"order\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"a\"",
    "\"at\"",
    "\"abort\"",
    "\"appending\"",
    "\"background\"",
    "\"buffer\"",
    "\"by\"",
    "\"call\"",
    "\"cell\"",
    "\"cells\"",
    "\"click\"",
    "\"countdown\"",
    "\"cursor\"",
    "\"display\"",
    "\"duration\"",
    "\"else\"",
    "\"field\"",
    "\"file\"",
    "\"flush\"",
    "\"font\"",
    "\"for\"",
    "\"from\"",
    "\"hide\"",
    "\"html\"",
    "\"if\"",
    "\"image\"",
    "\"is\"",
    "\"into\"",
    "\"key\"",
    "\"load\"",
    "\"log\"",
    "\"move\"",
    "\"movie\"",
    "\"of\"",
    "\"or\"",
    "\"pause\"",
    "\"plain\"",
    "\"play\"",
    "\"proc\"",
    "\"removing\"",
    "\"rich\"",
    "\"repeat\"",
    "\"row\"",
    "\"rows\"",
    "\"second\"",
    "\"seconds\"",
    "\"set\"",
    "\"show\"",
    "\"size\"",
    "\"skip\"",
    "\"slider\"",
    "\"sound\"",
    "\"start\"",
    "\"text\"",
    "\"timer\"",
    "\"to\"",
    "\"until\"",
    "\"using\"",
    "\"wait\"",
    "\"waiting\"",
    "\"while\"",
    "\"with\"",
    "\"without\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<CHARACTER>",
    "<VARIABLE>",
  };

}
